# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageVersion: '$(ImageName):$(build.buildId)'

steps:
  - script: |
      cd $(JavasampleDockerfileFolderPath)
      docker build -f Dockerfile -t $(ContainerRegistryUri)/$(imageVersion) .
    displayName: 'docker build'
  - script: |
      docker login -u $(ContainerRegistryUsername) -p $(ContainerRegistryPassword) $(ContainerRegistryUri)
      docker push $(ContainerRegistryUri)/$(imageVersion)
    displayName: 'Push docker image'
  - task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/$(JavasampleDockerfileFolderPath)
    contents: 'docker-compose.yml'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
