# Default values for deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  ## Enable Ingress resource creation
  # enabled: true
  hostname: VALUE_TO_BE_OVERRIDDEN
  annotations:
     kubernetes.io/ingress.class: addon-http-application-routing
  ## Enable Ingress TLS
  # tls: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

applicationInsights:
  InstrumentationKey: VALUE_TO_BE_OVERRIDDEN
