apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.name" . }}
  labels:
    app: {{ template "deployment.name" . }}
    chart: {{ template "deployment.chart" . }}
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "deployment.name" . }}
